### ISSUE TITLE
OS Error on CentOS 7

### ISSUE THREAD

**Issue by valmar** [nix-community/nix-user-chroot#7] opened 2019-04-25 11:27 UTC
When using nix-user-chroot on CentOS 7, I get the following error running the installation

```
./nix-user-chroot ~/.nix bash -c "curl https://nixos.org/nix/install | bash" 
failed to execute bash: No such file or directory (os error 2)
```

This is the version of CentOS I am running on:

```
centos-release-7-6.1810.2.el7.centos.x86_64
```

Namespaces seem to be available:

```
unshare --user --pid echo YES
YES
```

Thanks for any help you can provide!

**Comment by Mic92** [comment] 2019-04-25 14:39
So this one also fails?

```
$ ./nix-user-chroot ~/.nix bash -c "hello world"
```

**Comment by valmar** [comment] 2019-04-25 14:53
Unfortunately, yes:

```
./nix-user-chroot ~/.nix bash -c "echo hello world"
failed to execute bash: No such file or directory (os error 2)
```

**Comment by valmar** [comment] 2019-04-25 14:55
I have a question. Should something be in .nix? Currently, I just create the directory and run the installer, but there is no store or anything in ~/.nix. Should bash come from there? Or the system?

**Comment by Mic92** [comment] 2019-04-25 15:00
It should come from the system in that case.

**Comment by valmar** [comment] 2019-04-25 15:08
Bash is in /usr/bin/bash. I tried to put this explicitely in the PATH. Same result. I am a little wary of showing the output of strace because it reveals some information about the layout of our cluster and that could land me in trouble with the company I work for. 

However, it seems that several version of bash are found on the system. The strace has 6-7 lines like:

```
[pid 64881] execve(<redacted path to one version of bash>, ["bash", "-c", "echo hello world"], [/* 62 vars */]) = -1 ENOENT (No such file or directory)
```

**Comment by zimbatm** [comment] 2019-04-25 15:13
that smells like a ld loader issue. maybe the sandbox is preventing .so files from being loaded

**Comment by Mic92** [comment] 2019-04-25 15:16
It should not shadow `/lib` so. You could try running:

```
./nix-user-chroot ldd /usr/bin/bash
```

**Comment by valmar** [comment] 2019-04-25 15:23
First of all, thank you all for all this help. Sadly, I don't know Rust, or I would try to help too!
Secondly: ldd does not run, same error:

```
[vmariani@max-cfel001 ~]$ ./nix-user-chroot ~/.nix ldd /usr/bin/bash
failed to execute ldd: No such file or directory (os error 2)
```

**Comment by valmar** [comment] 2019-04-25 15:26
Wait wait wait. The execve error do not show the real paths to versions of bash (or ldd) in the system. They just show 'bash' or 'ldd' appended to each path in my PATH....

The first path tried is /usr/bin/bash, which exists. Nevertheless, the error says:
```
...
 brk(0x19ea000)              = 0x19ea000
[pid 15844] brk(0x19eb000)              = 0x19eb000
[pid 15844] brk(0x19ec000)              = 0x19ec000
[pid 15844] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 15844] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x4349ed}, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x4349ed}, 8) = 0
[pid 15844] execve("/usr/bin/bash", ["bash", "echo", "hello world"], [/* 62 vars */]) = -1 ENOENT (No such file or directory)
....
```

**Comment by valmar** [comment] 2019-04-27 12:58
Is it possible that the command is looking for those paths inside the sandbox? Is there a way to test this?

Valerio

**Comment by Mic92** [comment] 2019-04-30 11:20
What is the kernel version that centos uses? Maybe it reproducible in NixOS this way as well.

**Comment by valmar** [comment] 2019-04-30 12:12
Thanks for looking into this!

This is the kernel:

Linux <redacted hostname> 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 
14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Valerio

**Comment by Mic92** [comment] 2019-05-01 13:29
Mhm. This is older then the oldest kernel available in NixOS.

**Comment by valmar** [comment] 2019-05-01 13:36
This is the kernel in the centos 7 installation that my company 
has..... According to the tests, it shoud support namespaces.

I had been hoping to use nix on it (I don't have root access, of course)

**Comment by valmar** [comment] 2019-05-02 21:32
I could reproduce the issue on a fresh CentOS 7 installation  in a virtual machine.
This allows me to post the strace without issues. Here it is:

```
strace -f ./nix-user-chroot ~/.nix bash -c "echo hello world"
execve("./nix-user-chroot", ["./nix-user-chroot", "/home/vmariani/.nix", "bash", "-c", "echo hello world"], [/* 49 vars */]) = 0
mmap(NULL, 448, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8029cb4000
arch_prctl(ARCH_SET_FS, 0x7f8029cb40c0) = 0
set_tid_address(0x7f8029cb4100)         = 16406
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x4349ed}, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGSEGV, {0x41ec10, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x4349ed}, NULL, 8) = 0
rt_sigaction(SIGBUS, {0x41ec10, [], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x4349ed}, NULL, 8) = 0
sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8029cb2000
sigaltstack({ss_sp=0x7f8029cb2000, ss_flags=0, ss_size=8192}, NULL) = 0
brk(NULL)                               = 0x177d000
brk(0x177e000)                          = 0x177e000
getrandom("", 0, 0)                     = 0
getrandom("K.1ao\352\354\236\345\372T\220\2\311\305+C\246\33Kk\1\225\304\360TH\225\302\231\374\311"..., 2048, 0) = 2048
brk(0x1780000)                          = 0x1780000
mkdir("/tmp/nix.hmwbLyfPLgPn", 0777)    = 0
open("/home/vmariani/.nix", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_PATH) = 3
readlink("/proc/self/fd/3", "/home/vmariani/.nix", 4095) = 19
fstat(3, {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
stat("/home/vmariani/.nix", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
close(3)                                = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 16407
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(16407, strace: Process 16407 attached
 <unfinished ...>
[pid 16407] gettid()                    = 16407
[pid 16407] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 16407] getcwd("/home/vmariani/Documents", 512) = 25
[pid 16407] getuid()                    = 1000
[pid 16407] getgid()                    = 1000
[pid 16407] unshare(CLONE_NEWNS|CLONE_NEWUSER) = 0
[pid 16407] mount("/tmp/nix.hmwbLyfPLgPn", "/tmp/nix.hmwbLyfPLgPn", 0x7fffdcf48d48, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] mount("/tmp/nix.hmwbLyfPLgPn", "/tmp/nix.hmwbLyfPLgPn", 0x7fffdcf48d48, MS_REC|MS_PRIVATE, 0x43f936) = 0
[pid 16407] mkdir("/tmp/nix.hmwbLyfPLgPn/nix", 0777) = 0
[pid 16407] pivot_root("/tmp/nix.hmwbLyfPLgPn", "/tmp/nix.hmwbLyfPLgPn/nix") = 0
[pid 16407] chdir("/")                  = 0
[pid 16407] open("/nix", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 3
[pid 16407] fcntl(3, F_SETFD, FD_CLOEXEC) = 0
[pid 16407] getdents64(3, /* 21 entries */, 2048) = 520
[pid 16407] newfstatat(3, "boot", {st_mode=S_IFDIR|0555, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/boot", 0777)        = 0
[pid 16407] mount("/nix/boot", "/boot", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "dev", {st_mode=S_IFDIR|0755, st_size=3200, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/dev", 0777)         = 0
[pid 16407] mount("/nix/dev", "/dev", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "proc", {st_mode=S_IFDIR|0555, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/proc", 0777)        = 0
[pid 16407] mount("/nix/proc", "/proc", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "run", {st_mode=S_IFDIR|0755, st_size=1300, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/run", 0777)         = 0
[pid 16407] mount("/nix/run", "/run", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "sys", {st_mode=S_IFDIR|0555, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/sys", 0777)         = 0
[pid 16407] mount("/nix/sys", "/sys", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "etc", {st_mode=S_IFDIR|0755, st_size=8192, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/etc", 0777)         = 0
[pid 16407] mount("/nix/etc", "/etc", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "root", {st_mode=S_IFDIR|0550, st_size=220, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/root", 0777)        = 0
[pid 16407] mount("/nix/root", "/root", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "var", {st_mode=S_IFDIR|0755, st_size=282, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/var", 0777)         = 0
[pid 16407] mount("/nix/var", "/var", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/tmp", 0777)         = 0
[pid 16407] mount("/nix/tmp", "/tmp", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "usr", {st_mode=S_IFDIR|0755, st_size=155, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/usr", 0777)         = 0
[pid 16407] mount("/nix/usr", "/usr", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "bin", {st_mode=S_IFLNK|0777, st_size=7, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] newfstatat(3, "sbin", {st_mode=S_IFLNK|0777, st_size=8, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] newfstatat(3, "lib", {st_mode=S_IFLNK|0777, st_size=7, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] newfstatat(3, "lib64", {st_mode=S_IFLNK|0777, st_size=9, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] newfstatat(3, "home", {st_mode=S_IFDIR|0755, st_size=22, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/home", 0777)        = 0
[pid 16407] mount("/nix/home", "/home", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "media", {st_mode=S_IFDIR|0755, st_size=6, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/media", 0777)       = 0
[pid 16407] mount("/nix/media", "/media", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "mnt", {st_mode=S_IFDIR|0755, st_size=6, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/mnt", 0777)         = 0
[pid 16407] mount("/nix/mnt", "/mnt", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "opt", {st_mode=S_IFDIR|0755, st_size=48, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/opt", 0777)         = 0
[pid 16407] mount("/nix/opt", "/opt", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] newfstatat(3, "srv", {st_mode=S_IFDIR|0755, st_size=6, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 16407] mkdir("/srv", 0777)         = 0
[pid 16407] mount("/nix/srv", "/srv", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] getdents64(3, /* 0 entries */, 2048) = 0
[pid 16407] close(3)                    = 0
[pid 16407] mount("/home/vmariani/.nix", "/nix", 0x7fffdcf48dd8, MS_BIND|MS_REC, 0x43f936) = 0
[pid 16407] open("/proc/self/setgroups", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
[pid 16407] fcntl(3, F_SETFD, FD_CLOEXEC) = 0
[pid 16407] fcntl(3, F_GETFD)           = 0x1 (flags FD_CLOEXEC)
[pid 16407] write(3, "deny", 4)         = 4
[pid 16407] close(3)                    = 0
[pid 16407] open("/proc/self/uid_map", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
[pid 16407] fcntl(3, F_SETFD, FD_CLOEXEC) = 0
[pid 16407] write(3, "1000 1000 1", 11) = 11
[pid 16407] open("/proc/self/gid_map", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 4
[pid 16407] fcntl(4, F_SETFD, FD_CLOEXEC) = 0
[pid 16407] write(4, "1000 1000 1", 11) = 11
[pid 16407] chdir("/home/vmariani/Documents") = 0
[pid 16407] brk(0x1781000)              = 0x1781000
[pid 16407] brk(0x1782000)              = 0x1782000
[pid 16407] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 16407] rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x4349ed}, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x4349ed}, 8) = 0
[pid 16407] execve("/home/vmariani/.cargo/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/home/vmariani/.cargo/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/usr/local/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/usr/local/sbin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/usr/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/usr/sbin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/sbin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/home/vmariani/.local/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] execve("/home/vmariani/bin/bash", ["bash", "-c", "echo hello world"], [/* 50 vars */]) = -1 ENOENT (No such file or directory)
[pid 16407] write(2, "failed to execute ", 18failed to execute ) = 18
[pid 16407] write(2, "bash", 4bash)         = 4
[pid 16407] write(2, ": ", 2: )           = 2
[pid 16407] write(2, "No such file or directory", 25No such file or directory) = 25
[pid 16407] write(2, " (os error ", 11 (os error ) = 11
[pid 16407] write(2, "2", 12)            = 1
[pid 16407] write(2, ")", 1))            = 1
[pid 16407] write(2, "\n", 1
)           = 1
[pid 16407] sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
[pid 16407] munmap(0x7f8029cb2000, 8192) = 0
[pid 16407] exit_group(1)               = ?
[pid 16407] +++ exited with 1 +++
<... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], WSTOPPED, NULL) = 16407
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=16407, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
lstat("/tmp/nix.hmwbLyfPLgPn", {st_mode=S_IFDIR|0775, st_size=188, ...}) = 0
open("/tmp/nix.hmwbLyfPLgPn", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
getdents64(3, /* 18 entries */, 2048)   = 440
open("/tmp/nix.hmwbLyfPLgPn/nix", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/nix")      = 0
open("/tmp/nix.hmwbLyfPLgPn/boot", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/boot")     = 0
open("/tmp/nix.hmwbLyfPLgPn/dev", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/dev")      = 0
open("/tmp/nix.hmwbLyfPLgPn/proc", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/proc")     = 0
open("/tmp/nix.hmwbLyfPLgPn/run", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/run")      = 0
open("/tmp/nix.hmwbLyfPLgPn/sys", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/sys")      = 0
open("/tmp/nix.hmwbLyfPLgPn/etc", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/etc")      = 0
open("/tmp/nix.hmwbLyfPLgPn/root", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/root")     = 0
open("/tmp/nix.hmwbLyfPLgPn/var", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/var")      = 0
open("/tmp/nix.hmwbLyfPLgPn/tmp", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/tmp")      = 0
open("/tmp/nix.hmwbLyfPLgPn/usr", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/usr")      = 0
open("/tmp/nix.hmwbLyfPLgPn/home", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/home")     = 0
open("/tmp/nix.hmwbLyfPLgPn/media", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/media")    = 0
open("/tmp/nix.hmwbLyfPLgPn/mnt", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/mnt")      = 0
open("/tmp/nix.hmwbLyfPLgPn/opt", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/opt")      = 0
open("/tmp/nix.hmwbLyfPLgPn/srv", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 4
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
getdents64(4, /* 2 entries */, 2048)    = 48
getdents64(4, /* 0 entries */, 2048)    = 0
close(4)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn/srv")      = 0
getdents64(3, /* 0 entries */, 2048)    = 0
close(3)                                = 0
rmdir("/tmp/nix.hmwbLyfPLgPn")          = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7f8029cb2000, 8192)            = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by Mic92** [comment] 2019-05-03 05:20
Would it be possible to upgrade the kernel in the same virtual machine and see if that solves the issue?

**Comment by Mic92** [comment] 2019-05-03 05:54
I am currently not so motivated to go through a centos installation. It could be the case that some directories/symlinks are not properly bind mounted. I don't see `/lib` for example. Also I don't know if Centos still uses this.

**Comment by valmar** [comment] 2019-05-03 08:06
@Mic92 Thanks! I updated the kernel in the CentOS virtual machine to 5.0.11 but the error still persists. I checked, and the /lib directory is there.

I understand you lack of motivation. What I could do to facilitate your work in this direction is to create a CentOS VPS say, on Hetzner or Digital Ocean (for which I would pay) and make it available to you. I am very keen on seeing this run on CentOS because nix is a very good candidate to be used on clusters where one does not have root access, and most clusters I know (In academia, where I work) use RHEL or CentOS.

However, I understand that you might not be motivated to work on this and I thank you for all the effort you have already undertook.

**Comment by valmar** [comment] 2019-05-03 08:13
I also thought it could be SELINUX and tried to disable it, but the problem is still there

**Comment by valmar** [comment] 2019-05-03 09:22
I also tested right now on a just installed Fedora 30 on my laptop. Same problem!

**Comment by Mic92** [comment] 2019-05-03 09:37
An ssh account with root access would work for me. You can contact me via IRC via Mic92 on freenode.

**Comment by valmar** [comment] 2019-05-03 10:00
Perfect! I will let you know, thank you so much!

**Comment by zimbatm** [comment] 2019-05-03 11:06
The problem is that centos has a bunch of symlinks in the root:
```
lrwxrwxrwx   1 root root     7 Mar  5 17:34 bin -> usr/bin
lrwxrwxrwx   1 root root     7 Mar  5 17:34 lib -> usr/lib
lrwxrwxrwx   1 root root     9 Mar  5 17:34 lib64 -> usr/lib64
lrwxrwxrwx   1 root root     8 Mar  5 17:34 sbin -> usr/sbin
```
And nix-user-chroot ignores all the non-folders:
https://github.com/nix-community/nix-user-chroot/blob/186348f7329adad5246f0d5dd55a37db5d14ae67/src/main.rs#L30-L32

**Comment by valmar** [comment] 2019-05-03 13:23
@zimbatm Fedora too, so that could be it!

@Mic92 in light of @zimbatm 's report, do you still need the VPS? It is ready!

**Comment by Mic92** [comment] 2019-05-03 13:51
This is what I suspected too, I don't need it in that case.

**Comment by valmar** [comment] 2019-05-03 14:21
@Mic92 I will keep it around for a few days just in case. Do you think that the problem can be fixed (no hurry, of course!)

**Comment by Mic92** [comment] 2019-05-04 23:44
fixed in https://github.com/nix-community/nix-user-chroot/releases/tag/1.0.2

**Closed by Mic92** 2019-05-04 23:44 UTC
